### ISSUE TITLE
Add libraries and packages dependencies in readme + remove useless packages

### ISSUE THREAD

**Issue by ismaRP** [acortell3/archaeoriddle#15]
Since this is not a package yet, the dependencies are not automatically taken care of.
So we could add them to the github readme in case people want to implement and run the functions themselves.

At least for me running Ubuntu there are a couple of libraries that I had to install separately: libgdal-dev, libudunits2-dev and libgeos-dev
It was not a problem, they got indicated when I tried to install `terra` (although libgdal-dev was not directly mentioned), but it would be nice to have them all in one place.

**Comment by simoncarrignon** [comment]
To me this sounds done, also we could add in the README the Debian/Ubuntu packages that are needed to install all these packages...

**Comment by acortell3** [comment]
Yep, I think that would be a good idea... It's not really necessary, since unlike me, Ubuntu/Debian users should already be aware that they have to install some dependencies independently, but it certainly wouldn't hurt... I did write down all the packages (lib*) I had to install in the command line, so it's easy to do... I should be able to modify the readme today
